name: Create Release

on:
  push:
    branches:
      - main

jobs:
  verify:
    uses: ./.github/workflows/check.yml
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v2
  build:
    runs-on: ubuntu-latest
    needs: 
      - get-next-version
      - verify
    steps:
      - uses: actions/checkout@v4
      - name: Install Semantic Release Cargo
        if: needs.get-next-version.outputs.new-release-published == 'true'
        uses: EricCrosson/install-github-release-binary@v2
        with:
          targets: semantic-release-cargo@2
      - name: Prepare semantic-release for Rust
        if: needs.get-next-version.outputs.new-release-published == 'true'
        run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}

